GET http://localhost:3001/api/persons/

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "zxc",
    "number": 127777
}


###
DELETE http://localhost:3001/api/delete/2